spring:
  application:
    name: comment-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 10000
        max-attempts: 20
        initial-interval: 2000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    retry:
      max-interval: 10000
      max-attempts: 20
      initial-interval: 2000