server:
  port: 0

stats-server:
  name: stats-server

spring:
  application:
    name: comment-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/comment_db
    username: comment_user
    password: password1
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace