server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/*/events/**, /events/**, /admin/categories/**, /categories/**, /admin/compilations/**, /compilations/**
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**, /users/{userId}/comments/**, /events/{eventId}/comments/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE