server:
  port: 0

grpc:
  server:
    port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/analyzer_db
    driver-class-name: org.postgresql.Driver
    username: analyzer_user
    password: password5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

kafka:
  consumer:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}

analyzer:
  topic:
    user:
      v1: stats.user-actions.v1
    event:
      v1: stats.events-similarity.v1